In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
data = pd.read_csv("customer_churn_data.csv")
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST0000,Male,0,No,Yes,23,No,No phone service,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer,49.85,1146.55,No
1,CUST0001,Female,0,Yes,No,43,No,No phone service,DSL,Yes,...,Yes,No,Yes,No,Month-to-month,No,Mailed check,100.70,4330.10,Yes
2,CUST0002,Male,1,No,No,51,Yes,No,DSL,No,...,Yes,Yes,No,No,One year,No,Electronic check,97.33,4963.83,Yes
3,CUST0003,Male,1,No,No,72,Yes,Yes,DSL,Yes,...,Yes,No,No,No,Month-to-month,No,Credit card,101.38,7299.36,No
4,CUST0004,Male,1,No,No,25,Yes,Yes,DSL,No,...,No,Yes,No,Yes,Month-to-month,No,Electronic check,52.22,1305.50,Yes

In [3]:
data = data.dropna()

In [4]:
label_encoder = LabelEncoder()

for column in data.columns:
    if data[column].dtype == 'object':
        data[column] = label_encoder.fit_transform(data[column])

In [5]:
X = data.drop("Churn", axis=1)
y = data["Churn"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [7]:
X_train

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
3276,3276,1,1,0,1,30,0,1,0,0,2,0,2,0,0,2,1,0,59.20,1776.00
3116,3116,1,0,1,0,21,1,2,2,1,1,1,1,1,1,0,1,0,114.13,2396.73
3887,3887,1,0,0,1,63,1,2,1,2,2,2,2,2,0,1,0,0,27.65,1741.95
4903,4903,1,1,1,0,23,1,2,2,1,1,1,1,1,1,0,0,2,64.67,1487.41
3534,3534,0,0,0,0,39,1,0,0,2,0,0,2,2,2,1,1,3,76.96,3001.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,3772,0,0,0,1,68,1,0,1,0,0,0,2,2,0,0,1,3,26.72,1816.96
5191,5191,0,1,0,1,1,1,2,2,1,1,1,1,1,1,2,1,2,50.52,50.52
5226,5226,1,1,1,0,43,1,0,2,1,1,1,1,1,1,0,1,0,73.38,3155.34
5390,5390,0,1,1,0,39,1,2,2,1,1,1,1,1,1,0,0,3,48.47,1890.33
860,860,0,0,1,0,38,1,0,0,0,0,0,2,0,2,1,0,0,84.98,3229.24

In [8]:
X_test

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
5370,5370,0,1,1,0,20,0,1,2,1,1,1,1,1,1,2,1,0,101.69,2033.80
5299,5299,0,1,1,1,32,1,2,0,2,2,0,0,2,0,2,0,3,91.61,2931.52
199,199,1,1,1,0,24,1,2,0,2,0,0,0,2,2,0,0,0,115.58,2773.92
3268,3268,0,1,1,0,34,1,2,2,1,1,1,1,1,1,1,1,1,80.63,2741.42
3504,3504,1,0,0,0,67,1,0,1,0,2,0,2,2,2,1,0,2,70.29,4709.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4260,4260,1,0,1,0,38,1,0,1,2,0,2,2,0,2,2,0,3,74.77,2841.26
693,693,0,0,0,1,15,0,1,2,1,1,1,1,1,1,1,0,3,38.02,570.30
5386,5386,1,1,0,1,67,1,0,2,1,1,1,1,1,1,2,1,1,50.60,3390.20
4888,4888,1,1,0,1,10,1,0,0,2,2,0,2,2,2,2,1,0,114.36,1143.60
287,287,1,1,0,1,26,0,1,2,1,1,1,1,1,1,1,1,0,79.71,2072.46

In [9]:
y_train

3276    0
3116    1
3887    1
4903    0
3534    0
       ..
3772    0
5191    0
5226    1
5390    1
860     0
Name: Churn, Length: 4704, dtype: int64

In [10]:
y_test

5370    0
5299    1
199     0
3268    1
3504    0
       ..
4260    0
693     0
5386    1
4888    0
287     1
Name: Churn, Length: 1176, dtype: int64

In [12]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [13]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.4880952380952381

In [14]:
print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix
[[330 254]
 [348 244]]

In [15]:
print("\nClassification Report")
print(classification_report(y_test, y_pred))

Classification Report
              precision    recall  f1-score   support

           0       0.49      0.57      0.52       584
           1       0.49      0.41      0.45       592

    accuracy                           0.49      1176
   macro avg       0.49      0.49      0.49      1176
weighted avg       0.49      0.49      0.49      1176

In [17]:
result = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print("\nActual vs Predicted")
print(result.head(10))

Actual vs Predicted
   Actual  Predicted
0       0          1
1       1          0
2       0          1
3       1          0
4       0          1
5       0          1
6       0          0
7       0          1
8       0          1
9       1          0